### ISSUE TITLE
Cluster mRNA expression to identify outliers

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/pcbc_c4_analysis#14]
@th1vairam and I discussed clustering the mRNA expression matrix (both raw counts and normalized) to identify outlier samples. I will work with the existing matrix of data, but possibly extend to an eXpress based matrix.

**Comment by kdaily** [comment]
For normalized, I'll use the DESeq2 regularized log matrix; works well for exploratory analyses.

**Comment by th1vairam** [comment]
Did you commit your version of the clustering pipeline? or you want me to start with my own?

**Comment by kdaily** [comment]
Was digging for code I already had. I just ran the regularized log from
DESeq for all samples. Why don't you start with the raw counts using your
methods, and I'll start with the rlog, and we can merge?

**Comment by th1vairam** [comment]
Fine. Will do that on Monday

On Fri, Feb 27, 2015 at 5:12 PM, Kenneth Daily <notifications@github.com>
wrote:

> Was digging for code I already had. I just ran the regularized log from
> DESeq for all samples. Why don't you start with the raw counts using your
> methods, and I'll start with the rlog, and we can merge?
>
> On Fri, Feb 27, 2015 at 5:03 PM Thanneer Malai Perumal <
> notifications@github.com> wrote:
>
> > Did you commit your version of the clustering pipeline? or you want me to
> > start with my own?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Sage-Bionetworks/pcbc_c4_analysis/issues/14#issuecomment-76500723
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sage-Bionetworks/pcbc_c4_analysis/issues/14#issuecomment-76501286>
> .
>



-- 
Thanneer Malai Perumal
1835. Queen Anne Avenue North,
Apt: 205, Seattle,
Washington, USA - 98109
P: (+1) 206 229 1025

"Computers are to biology what mathematics is to physics.”
                                    — Harold Morowitz

**Comment by kdaily** [comment]
Probably when I'll start again too. Hopefully will have eXpress run by
then.

**Comment by kdaily** [comment]
Thaneer and I worked on this; he has a branch that contains our analysis. Once he opens a pull request I'll close this!

**Comment by th1vairam** [comment]
You can close this task now. Unless you wanna run same analysis on the eXpress aligned data.

**Comment by kdaily** [comment]
Thanks! Should make a new one I suppose, once that finishes I'll let you
know.
