### ISSUE TITLE
adjusted expression from voom$E matrix

### ISSUE THREAD

**Issue by lpantano** [Sage-Bionetworks/pcbc_c4_analysis#27]
Hi,

I was just curious about the file you call adjusted expression for the mRNA data. When I was playing with the miRNA data no matter but design matrix I was using that the object `*$E` from `voom` was always having the same values. I just wanted to check with you if it happens the same to you, and in that case the adjusted expression matrix is only a normalization matrix using this code inside voom package:

`y <- t(log2(t(counts+0.5)/(lib.size+1)*1e6))`

if not, how did you do to get different values from that matrix using different design?

thanks

**Comment by kdaily** [comment]
Voom converts the read counts to log2 -cpm, with associated weights - the
weights are what changes. Fitting using 'lmFit' from limma uses these
weights.

Kenny

**Comment by lpantano** [comment]
ok, that was I thought, I just was confusing about the name of the file 
because I thought that adjusted was meaning the expression was corrected 
according the design matrix. all good, thanks!

**Comment by kdaily** [comment]
Agreed - it is confusing. We can describe it better! - Kenny
